export const LOGINFAIL = 'LOGINFAIL';
export const LOGINSUCCESS = 'LOGINSUCCESS';
export const LOGOUT = 'LOGOUT';

export const SAVEPROFILE = 'SAVEPROFILE';
export const SAVEPROFILESUCCESS = 'SAVEPROFILESUCCESS';
export const SAVEPROFILEFAIL = 'SAVEPROFILEFAIL';

export const SAVEPROFILEDETALS = 'SAVEPROFILEDETALS';
export const SAVEPROFILEDETALSSUCCESS = 'SAVEPROFILEDETALSSUCCESS';
export const SAVEPROFILEDETALSFAIL = 'SAVEPROFILEDETALSFAIL';